name: build UMMLoader

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add Mono APT repository
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget -O - https://download.mono-project.com/repo/xamarin.asc | 
            sudo apt-key add -
          echo "deb https://download.mono-project.com/repo/xamarin/ubuntu/ 
            noble main" | sudo tee /etc/apt/sources.list.d/mono-official.list
          sudo apt-get update

      - name: Install Mono and MSBuild
        run: |
          sudo apt-get install -y mono-devel mono-msbuild
      - name: Build with MSBuild
        run: |
          export PATH=/usr/bin:$PATH
          msbuild /p:Configuration=Release /p:Platform=AnyCPU

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: UMMLoader
          path: UMMLoader/bin/Release/UMMLoader.dll
