name: build UMMLoader
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Mono
        run: |
          sudo apt update
          sudo apt install mono-devel -y
      - name: Build
        run: msbuild /p:Configuration=Release
      - name:  Upload artifact
        uses:  actions/upload-artifact@v4
        with:
          name: UMMLoader
          path: UMMLoader/bin/Release/UMMLoader.dll
